// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OutlookCalendarApi.Data;

#nullable disable

namespace OutlookCalendarApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309195915_AddSummitIdToInterviewSession")]
    partial class AddSummitIdToInterviewSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Habit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("habits", (string)null);
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.HabitEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CalendarEventId")
                        .HasColumnType("text")
                        .HasColumnName("calendar_event_id");

                    b.Property<int>("DurationMins")
                        .HasColumnType("integer")
                        .HasColumnName("duration_mins");

                    b.Property<Guid>("HabitPrescriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_prescription_id");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<TimeOnly?>("ScheduledTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_time");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("HabitPrescriptionId");

                    b.HasIndex("SprintId");

                    b.ToTable("habit_events", (string)null);
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.HabitPrescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("HabitId")
                        .HasColumnType("uuid")
                        .HasColumnName("habit_id");

                    b.Property<string>("Prescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prescription");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.HasKey("Id");

                    b.HasIndex("HabitId");

                    b.HasIndex("SprintId");

                    b.ToTable("habit_prescriptions", (string)null);
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Identity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("identities", (string)null);
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.InterviewSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccumulatedData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("accumulated_data");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ConversationHistory")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conversation_history");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer")
                        .HasColumnName("current_step");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<Guid?>("SummitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.HasIndex("SummitId");

                    b.HasIndex("UserId");

                    b.ToTable("interview_sessions", (string)null);
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Milestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ProofCriteria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proof_criteria");

                    b.Property<DateTime?>("ProvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proved_at");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("SummitId")
                        .HasColumnType("uuid")
                        .HasColumnName("summit_id");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.HasKey("Id");

                    b.HasIndex("SummitId");

                    b.ToTable("milestones", (string)null);
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("milestone_id");

                    b.Property<string>("Reflection")
                        .HasColumnType("text")
                        .HasColumnName("reflection");

                    b.Property<int>("SprintNumber")
                        .HasColumnType("integer")
                        .HasColumnName("sprint_number");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MilestoneId");

                    b.ToTable("sprints", (string)null);
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.SprintTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CalendarEventId")
                        .HasColumnType("text")
                        .HasColumnName("calendar_event_id");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMins")
                        .HasColumnType("integer")
                        .HasColumnName("duration_mins");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("SprintId");

                    b.ToTable("sprint_tasks", (string)null);
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Summit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<string>("ProofCriteria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proof_criteria");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date")
                        .HasColumnName("target_date");

                    b.HasKey("Id");

                    b.HasIndex("IdentityId");

                    b.ToTable("summits", (string)null);
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Habit", b =>
                {
                    b.HasOne("OutlookCalendarApi.Models.Domain.Identity", "Identity")
                        .WithMany("Habits")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.HabitEvent", b =>
                {
                    b.HasOne("OutlookCalendarApi.Models.Domain.HabitPrescription", "HabitPrescription")
                        .WithMany("HabitEvents")
                        .HasForeignKey("HabitPrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutlookCalendarApi.Models.Domain.Sprint", "Sprint")
                        .WithMany("HabitEvents")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HabitPrescription");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.HabitPrescription", b =>
                {
                    b.HasOne("OutlookCalendarApi.Models.Domain.Habit", "Habit")
                        .WithMany("HabitPrescriptions")
                        .HasForeignKey("HabitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OutlookCalendarApi.Models.Domain.Sprint", "Sprint")
                        .WithMany("HabitPrescriptions")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habit");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Identity", b =>
                {
                    b.HasOne("OutlookCalendarApi.Models.Domain.User", "User")
                        .WithMany("Identities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.InterviewSession", b =>
                {
                    b.HasOne("OutlookCalendarApi.Models.Domain.Identity", "Identity")
                        .WithMany()
                        .HasForeignKey("IdentityId");

                    b.HasOne("OutlookCalendarApi.Models.Domain.Summit", "Summit")
                        .WithMany()
                        .HasForeignKey("SummitId");

                    b.HasOne("OutlookCalendarApi.Models.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");

                    b.Navigation("Summit");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Milestone", b =>
                {
                    b.HasOne("OutlookCalendarApi.Models.Domain.Summit", "Summit")
                        .WithMany("Milestones")
                        .HasForeignKey("SummitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summit");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Sprint", b =>
                {
                    b.HasOne("OutlookCalendarApi.Models.Domain.Milestone", "Milestone")
                        .WithMany("Sprints")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.SprintTask", b =>
                {
                    b.HasOne("OutlookCalendarApi.Models.Domain.Sprint", "Sprint")
                        .WithMany("SprintTasks")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Summit", b =>
                {
                    b.HasOne("OutlookCalendarApi.Models.Domain.Identity", "Identity")
                        .WithMany("Summits")
                        .HasForeignKey("IdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Identity");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Habit", b =>
                {
                    b.Navigation("HabitPrescriptions");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.HabitPrescription", b =>
                {
                    b.Navigation("HabitEvents");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Identity", b =>
                {
                    b.Navigation("Habits");

                    b.Navigation("Summits");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Milestone", b =>
                {
                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Sprint", b =>
                {
                    b.Navigation("HabitEvents");

                    b.Navigation("HabitPrescriptions");

                    b.Navigation("SprintTasks");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.Summit", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("OutlookCalendarApi.Models.Domain.User", b =>
                {
                    b.Navigation("Identities");
                });
#pragma warning restore 612, 618
        }
    }
}
